[[pages]]
name = "Miscellaneous"
icon = "ğŸ—ƒï¸"
is_section = true

[[pages]]
path = "1_About_me.py"
name = "About Me"


[[pages]]
name = "GIS ? Something"
icon = "ğŸŒ" 
is_section = true 


[[pages]]
name = "Bogor Dalam Peta" 
path = "2_Bogor_dalam_peta.py"

[[pages]]
name = "Excel to shp converter" 
path = "excel_to_shp.py"

[[pages]]
name = "Automated Valuation Model" 
path = "avm beta.py"

[[pages]]
name = "Stats ? Something"
icon = "ğŸ“¶" 
is_section = true 

[[pages]]
name = "Performing regression with your data" 
path = "regression_analysis.py"


[[pages]]
name = "Regression enhanced random forests" 
path = "Rerf.py"



[[pages]]
name = "AI ? Something"
icon = "âœ¨" 
is_section = true 

[[pages]]
name = "Plaud Agent"
path = "Plaud.py" 





