[[pages]]
name = "Miscellaneous"
icon = "ğŸ“¦"  # safe fallback for "miscellaneous"
is_section = true

[[pages]]
path = "1_About_me.py"
name = "About Me"
icon = "ğŸ‘¨ğŸ»â€ğŸš€"

[[pages]]
name = "Some random Application (made for fun)"
icon = "ğŸ“¦"  # fallback for globe
is_section = true

[[pages]]
name = "Bogor Dalam Peta" 
path = "2_Bogor_dalam_peta.py"
icon = "ğŸ“¦"

[[pages]]
name = "Excel to shp converter" 
path = "excel_to_shp.py"
icon = "ğŸ“¦"

[[pages]]
name = "Statsmodel API for statistical analysis" 
path = "regression_analysis.py"
icon = "ğŸ“¦"

[[pages]]
name = "Geo-Point property analyst" 
path = "avm beta.py"
icon = "ğŸ“¦"

[[pages]]
name = "AI Assisted Statistic, Machine learning and python quiz"
icon = "ğŸ“¦"
path = "podomoro.py"

[[pages]]
name = "Research, Notebook and Data Story Telling"
icon = "ğŸŒ²"
is_section = true


[[pages]]
name = "Regression enhanced random forests" 
path = "Rerf.py"
icon = "ğŸŒ²"


[[pages]]
name = "Work Life Balance Analysis" 
path = "wlb.py"
icon = "ğŸŒ²"








