[[pages]]
name = "Miscellaneous"
icon = "ğŸ“¦"  # safe fallback for "miscellaneous"
is_section = true

[[pages]]
path = "1_About_me.py"
name = "About Me"
icon = "ğŸ‘¨ğŸ»â€ğŸš€"

[[pages]]
name = "GIS ? Something"
icon = "ğŸŒ"  # fallback for globe
is_section = true

[[pages]]
name = "Bogor Dalam Peta" 
path = "2_Bogor_dalam_peta.py"
icon = "ğŸ—ºï¸"

[[pages]]
name = "Excel to shp converter" 
path = "excel_to_shp.py"
icon = "ğŸ“„"

[[pages]]
name = "Property" 
path = "avm beta.py"
icon = "ğŸ "

[[pages]]
name = "Stats ? Something"
icon = "ğŸ“Š"
is_section = true

[[pages]]
name = "Performing regression with your data" 
path = "regression_analysis.py"
icon = "ğŸ“ˆ"

[[pages]]
name = "Regression enhanced random forests" 
path = "Rerf.py"
icon = "ğŸŒ²"


[[pages]]
name = "Work Life Balance Analysis" 
path = "wlb.py"
icon = "ğŸŒ²"

[[pages]]
name = "AI ? Playground Something"
icon = "ğŸ’¡"
is_section = true

# [[pages]]
# name = "Plaud Agent"
# path = "Plaud.py"
# icon = "ğŸ¤–"

# [[pages]]
# name = "Aing FARIS"
# path = "aingfaris.py"
# icon = "ğŸ¤–"

# [[pages]]
# name = "Aing Indro"
# path = "indera_ai.py"
# icon = "ğŸ¤–"


# [[pages]]
# name = "RBCM-LITE"
# icon = "ğŸ“Š"
# path = "rbcm_lite.py"


[[pages]]
name = "Statistic, Machine learning and python quiz"
icon = "ğŸ“Š"
path = "podomoro.py"



